spring:
  application:
    name: feign
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

      
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0
  
item-service:
  ribbon:
#    ConnectTimeout: 500
#    ReadTimeout: 1000
#    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 0


feign:
  hystrix:
    enabled: true     
    
    
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
    

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream    
    