spring:
  application:
    name: config-server
    spring:
  rabbitmq:
    host: 192.168.193.135
    port: 5672
    username: admin
    password: admin
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/config
      
#        git:
#          uri: https://github.com/zhangxiangwu/config
#          searchPaths: config
          
          
          
server:
  port: 6001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka        
      
      
      
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
        
        
              